# English (United States) translations for PROJECT.
# Copyright (C) 2025 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-08-21 22:15+0800\n"
"PO-Revision-Date: 2025-08-21 14:30+0800\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: en_US\n"
"Language-Team: en_US <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: routers/v1/orsdm.py:165
msgid ""
"Task already exists, not allowed to duplicate one, please check odm "
"server."
msgstr "Task already exists. Duplicate tasks are not allowed. Please check the ODM server."

#: routers/v1/orsdm.py:179
msgid ""
"No images found in the specified folder. and the job has been removed "
"from the odm."
msgstr "No images found in the specified folder. The job has been removed from the ODM server."

#: routers/v1/orsdm.py:247
msgid "Odm task not found"
msgstr "ODM task not found"

#: routers/v1/orsdm.py:292 routers/v1/orsdm.py:340 routers/v1/orsdm.py:394
#: routers/v1/orsdm.py:452
msgid "Job not found"
msgstr "Job not found"

#: routers/v1/orsdm.py:301
msgid "Failed to cancel celery task."
msgstr "Failed to cancel the Celery task"

#: routers/v1/orsdm.py:304
msgid "Failed to remove ODM task from odm server."
msgstr "Failed to remove the ODM task from the ODM server"

#: routers/v1/orsdm.py:344
msgid "ODM task must be completed, failed, or canceled before it can be removed."
msgstr "The ODM task must be completed, failed, or canceled before it can be removed"

#: routers/v1/orsdm.py:379
msgid "Orthophoto tif file not provided"
msgstr "Orthophoto TIFF file not provided"

#: routers/v1/orsdm.py:386
msgid "Orthophoto tif file not found"
msgstr "Orthophoto TIFF file not found"

#: routers/v1/orsdm.py:535 routers/v1/orsdm.py:646 routers/v1/orsdm.py:726
msgid "Report not found, please try again later."
msgstr "Report not found. Please try again later."

#: routers/v1/orsdm.py:649
msgid "Report is already uploaded."
msgstr "Report has already been uploaded"

#: routers/v1/orsdm.py:736
msgid "Report is not running. Cannot cancel."
msgstr "Report is not running. Cannot be canceled"

#: utils/cersdm.py:482
#, python-format
msgid ""
"Committed Cloud ODM report failed. Error code: %(error_code)d, Message: "
"%(error_message)s"
msgstr "Failed to commit Cloud ODM report. Error code: %(error_code)d, Message: %(error_message)s"

#: utils/cersdm.py:484
msgid "Unknown error"
msgstr "Unknown error"
